[meta-arm]
src_uri = https://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = master
last_revision = 3681201897f164408194e4cc823e1e3650607dab

[meta-openembedded]
src_uri = https://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = master
last_revision = d8cb988be342bc887d71ae68ede38cc013e552ea

[meta-raspberrypi]
src_uri = https://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = master
last_revision = 0c76b0feadbe2afa4cec4cd497636e94eca30ec3

[meta-security]
src_uri = https://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = master
last_revision = 226839ac408223f8041cde1b1d8b762d6fbc8050

[openembedded-core]
src_uri = https://git.openembedded.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = master
last_revision = 866915fa7bcbe563849aa1100033c684a805fc24

[bitbake]
src_uri = https://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = master
last_revision = 94fbae4aa114e40d4ac57d5b1a19aacc86f0e10d

[yocto-docs]
src_uri = https://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = master
last_revision = be424bf52cd3ac9c83a4617d0b06afe8cde055be

