[meta-arm]
src_uri = https://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = master
last_revision = 28606c721503b70e8343968731a24260cfe985bc

[meta-openembedded]
src_uri = https://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = master
last_revision = 17afdec9d85fa4642a5b9163fa0014b4a1bfc764

[meta-raspberrypi]
src_uri = https://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = master
last_revision = b0f0a6c0bfbf5d0e464c13944dda73fa69f31f6b

[meta-security]
src_uri = https://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = master
last_revision = 226839ac408223f8041cde1b1d8b762d6fbc8050

[openembedded-core]
src_uri = https://git.openembedded.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = master
last_revision = 5a5f2ec43cbb9096f1fc52ba4c2a4f94526f103d

[bitbake]
src_uri = https://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = master
last_revision = c251833d2062ef92fc7e77ab6456af928ad1d31a

[yocto-docs]
src_uri = https://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = master
last_revision = def10b40398732ff73f23bf9cb8c0288a8ad7640

