[meta-arm]
src_uri = https://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = master
last_revision = 02d361b4359fde9b6646129980f1484f7aa5b09e

[meta-openembedded]
src_uri = https://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = master
last_revision = 39321ae90b64e8f2bd890a2957a5f80e74d4de30

[meta-raspberrypi]
src_uri = https://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = master
last_revision = b4603a63b13e052a0f08761697fb5116a394bf64

[meta-security]
src_uri = https://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = master
last_revision = 226839ac408223f8041cde1b1d8b762d6fbc8050

[openembedded-core]
src_uri = https://git.openembedded.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = master
last_revision = 31edc0b82a3dc7b1dd0338da4a8d0d8f5a1dc138

[bitbake]
src_uri = https://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = master
last_revision = e74cfd03afe5aff1f81cbff8c6efcef77c9af618

[yocto-docs]
src_uri = https://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = master
last_revision = d7376cca64a0784e59d4fd60b9baefb4da2ce289

