[meta-arm]
src_uri = https://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = wrynose
last_revision = 052c2cf333ecf16fc2ded4c5d09749ebaff8c0c5

[meta-openembedded]
src_uri = https://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = wrynose
last_revision = 420222862f5a6d95023b8f5f3b7e1808b2264ef9

[meta-raspberrypi]
src_uri = https://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = master
last_revision = b4603a63b13e052a0f08761697fb5116a394bf64

[meta-security]
src_uri = https://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = wrynose
last_revision = 925357d25af4534807647d2a1d99e5b6c6df3af4

[openembedded-core]
src_uri = https://git.openembedded.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = wrynose
last_revision = 080e184ad9a07b469da7e8b045a93cefd5bf2438

[bitbake]
src_uri = https://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = 2.18
last_revision = 0415a00658b59f66bdab22a3558794f238c42973

[yocto-docs]
src_uri = https://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = wrynose
last_revision = 6b78593bed7174245fd7f6861263c69a3c439a74

