[meta-arm]
src_uri = https://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = wrynose
last_revision = 673e8d7c5dcd14de58092eb73e6ecc5eee5c1735

[meta-openembedded]
src_uri = https://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = wrynose
last_revision = 47d7dbdd10890bbd429bc0cccbe14435c37e5af1

[meta-raspberrypi]
src_uri = https://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = wrynose
last_revision = b2669c24bb577e1a48d841a60cfc0719f9ee1ff4

[meta-security]
src_uri = https://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = wrynose
last_revision = 2703974d5e2d61b221dffa302c2e059a522adbf3

[openembedded-core]
src_uri = https://git.openembedded.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = wrynose
last_revision = 0f03c732a0a2d0506b41b1abe60b3f368b2300dc

[bitbake]
src_uri = https://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = 2.18
last_revision = 51fd94a67fa17650a9ff623492005972bbc7d26f

[yocto-docs]
src_uri = https://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = wrynose
last_revision = a2cc1f5b86f3cdc9ad3257a2545322c5169da3ca

