[meta-arm]
src_uri = https://git.yoctoproject.org/meta-arm
dest_dir = upstream-layers/meta-arm
branch = wrynose
last_revision = d3b55902fb9963978be90d6f283296de456b4b63

[meta-openembedded]
src_uri = https://git.openembedded.org/meta-openembedded
dest_dir = upstream-layers/meta-openembedded
branch = wrynose
last_revision = 9af4488d46cb4fd4c0d2d64820c86225ebd6ac71

[meta-raspberrypi]
src_uri = https://git.yoctoproject.org/meta-raspberrypi
dest_dir = upstream-layers/meta-raspberrypi
branch = master
last_revision = ba2fa52ad7b4000f2bc510a76b3eb313ffc6b5ac

[meta-security]
src_uri = https://git.yoctoproject.org/meta-security
dest_dir = upstream-layers/meta-security
branch = wrynose
last_revision = c0d1d6200e7a84c39fb940cb1f22aad4b0b3d808

[openembedded-core]
src_uri = https://git.openembedded.org/openembedded-core
dest_dir = upstream-layers/openembedded-core
branch = wrynose
last_revision = 06dd66e6220e5ce4ed4b9af4d8231ae5f0a8ce80

[bitbake]
src_uri = https://git.openembedded.org/bitbake
dest_dir = upstream-layers/bitbake
branch = 2.18
last_revision = 22021758e66737bcf68dfd2b74adc6a0cb1d42d9

[yocto-docs]
src_uri = https://git.yoctoproject.org/yocto-docs
dest_dir = upstream-layers/yocto-docs
branch = wrynose
last_revision = 7ac955621b36a221126cd40f12c41fa98c213a24

